server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: recruitment-website
  jackson:
    serialization:
      write-dates-as-timestamps: false
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: Asia/Shanghai
